<template>
  <species-richness-introduction
    :filters="filters"
    :have-data="haveData"
  />
  <comparison-list-component
    class="mt-5"
    @emit-select="onFilterChange"
  />
  <horizontal-bar-chart-component
    dom-id="species-by-class"
    chart-title="Distinct species by taxonomic class"
    :chart-data="chartData"
    :chart-export-name="chartExportName"
    class="mt-5"
  />
  <species-richness-by-location
    :datasets="mapDatasets"
    class="mt-5"
  />
  <species-richness-by-time
    dom-id="species-by-time"
    :datasets="speciesByTimeDatasets"
    class="mt-5"
  />
  <species-richness-detected-species
    :table-data="tableData"
    :colors="colors"
    class="mt-5"
  />
</template>
<script src="./species-richness.ts" lang="ts"></script>
