apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: 'http'
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: bio-basic-auth-secrets
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  name: biodiversity-website-ingress
  namespace: testing
  labels:
    app: biodiversity-website
spec:
  rules:
    - host: testing-bio.rfcx.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: biodiversity-website-service
              servicePort: 80
    - host: preview.arbimon.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: biodiversity-website-service
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: 'http'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: biodiversity-website-with-api-ingress
  namespace: testing
  labels:
    app: biodiversity-website
spec:
  rules:
    - host: testing-bio.rfcx.org
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              serviceName: biodiversity-api-service
              servicePort: 80
