apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: 'http'
  name: biodiversity-website-ingress
  namespace: testing
  labels:
    app: biodiversity-website
spec:
  rules:
    - host: dev-insights.arbimon.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: biodiversity-website-service
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: 'http'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: biodiversity-website-with-api-ingress
  namespace: testing
  labels:
    app: biodiversity-website
spec:
  rules:
    - host: dev-insights.arbimon.org
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              serviceName: biodiversity-api-service
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: 'http'
  name: arbimon-landing-ingress
  namespace: testing
  labels:
    app: biodiversity-website
spec:
  rules:
  - host: dev.arbimon.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: biodiversity-website-service
          servicePort: 80
      - path: /api
        pathType: Prefix
        backend:
          serviceName: arbimon-service
          servicePort: 80
      - path: /auth0-login
        pathType: Prefix
        backend:
          serviceName: arbimon-service
          servicePort: 80
      - path: /fonts
        pathType: Prefix
        backend:
          serviceName: arbimon-service
          servicePort: 80
      - path: /images
        pathType: Prefix
        backend:
          serviceName: arbimon-service
          servicePort: 80
      - path: /includes
        pathType: Prefix
        backend:
          serviceName: arbimon-service
          servicePort: 80
      - path: /my-projects
        pathType: Prefix
        backend:
          serviceName: arbimon-service
          servicePort: 80
      - path: /project
        pathType: Prefix
        backend:
          serviceName: arbimon-service
          servicePort: 80
