apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: biodiversity-cli-opensearch-sync-incremental
  namespace: staging
spec:
  # every 15 minutes with 2 minutes offset, not running between 4AM GMT
  schedule: '2,17,32,47 0-3,5-23 * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: biodiversity-cli-opensearch-sync-incremental
            command: ["node", "--experimental-specifier-resolution=node", "apps/cli/lib/search/sync-incremental.js"]
            image: 887044485231.dkr.ecr.eu-west-1.amazonaws.com/biodiversity-cli:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: biodiversity-cli-secrets
              - configMapRef:
                  name: biodiversity-cli-config
          restartPolicy: Never
