apiVersion: batch/v1
kind: Job
metadata:
  name: biodiversity-cli-migrate-JOB_NUMBER
  namespace: staging
spec:
  template:
    spec:
      containers:
      - name: biodiversity-cli-migrate-JOB_NUMBER
        command: ["node", "--experimental-specifier-resolution=node", "apps/cli/lib/db-migrations/index.js"]
        image: 887044485231.dkr.ecr.eu-west-1.amazonaws.com/biodiversity-cli/testing:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: biodiversity-cli-secrets
          - configMapRef:
              name: biodiversity-cli-config
      restartPolicy: Never
  backoffLimit: 1