apiVersion: batch/v1
kind: Job
metadata:
  name: biodiversity-cli-migrate-JOB_NUMBER
  namespace: staging
spec:
  ttlSecondsAfterFinished: 86400 # delete finish job after a day
  template:
    metadata:
      labels:
        job_group: biodiversity-cli-migrate
    spec:
      containers:
      - name: biodiversity-cli-migrate-JOB_NUMBER
        command: ["node", "--experimental-specifier-resolution=node", "apps/cli/lib/db/migrate.js"]
        image: 887044485231.dkr.ecr.eu-west-1.amazonaws.com/biodiversity-cli:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: biodiversity-cli-secrets
          - configMapRef:
              name: biodiversity-cli-config
      restartPolicy: Never
  backoffLimit: 1