apiVersion: apps/v1
kind: Deployment
metadata:
  name: biodiversity-api
  namespace: staging
spec:
  selector:
    matchLabels:
      app: biodiversity-api
  template:
    metadata:
      labels:
        app: biodiversity-api
    spec:
      containers:
        - name: biodiversity-api
          image: 887044485231.dkr.ecr.eu-west-1.amazonaws.com/biodiversity-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: '200Mi'
              cpu: '200m'
            limits:
              memory: '400Mi'
              cpu: '400m'
          envFrom:
            - secretRef:
                name: biodiversity-api-secrets
            - configMapRef:
                name: biodiversity-api-config
