apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: staging
  name: job-creator
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: biodiversity-api
  namespace: staging
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: biodiversity-api-job-creator
  namespace: staging
subjects:
  - kind: ServiceAccount
    name: biodiversity-api
    namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-creator