apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: biodiversity-cli-opensearch-incremental-sync
  namespace: production
spec:
  # every 15 minutes
  schedule: '*/15 * * * *'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: biodiversity-cli-opensearch-incremental-sync
            command: ["node", "--experimental-specifier-resolution=node", "apps/cli/lib/search/incremental.js"]
            image: 887044485231.dkr.ecr.eu-west-1.amazonaws.com/biodiversity-cli:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: biodiversity-cli-secrets
              - configMapRef:
                  name: biodiversity-cli-config
          restartPolicy: Never
