# !WARNING: MANUAL ACTION REQUIRED!

# You must keep these file in sync:
# - `tools/deployment/api/production/config.yaml` -- CONFIG ONLY
# - `tools/deployment/api/staging/config.yaml` -- CONFIG ONLY
# - `tools/deployment/api/testing/config.yaml` -- CONFIG ONLY
# - `apps/api/.env.example` -- CONFIG & SECRETS
# - `apps/api/src/_services/env/keys.ts` -- CONFIG & SECRETS

apiVersion: v1
kind: ConfigMap
metadata:
  name: biodiversity-api-config
  namespace: production
data:
  ## Config
  AWS_S3_BUCKET_NAME: arbimon
  AWS_S3_BUCKET_REGION: eu-west-1
  AWS_OSS_REGION: eu-west-1
  ARBIMON_LEGACY_API_BASE_URL: https://arbimon.org/legacy-api
  CORE_API_BASE_URL: https://api.rfcx.org
  OPENSEARCH_ENABLED: "true"
