apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: biodiversity-cli-opensearch-full-reindex
  namespace: testing
spec:
  # every 15 minutes for testing
  schedule: '*/15 * * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: biodiversity-cli-opensearch-full-reindex
            command: ["node", "--experimental-specifier-resolution=node", "apps/cli/lib/search/main.js"]
            image: 887044485231.dkr.ecr.eu-west-1.amazonaws.com/biodiversity-cli:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: biodiversity-cli-secrets
              - configMapRef:
                  name: biodiversity-cli-config
          restartPolicy: Never
