apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: biodiversity-cli-sync-projects
spec:
  schedule: "10 17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: biodiversity-cli-sync-projects
            command: ["node", "--experimental-specifier-resolution=node", "apps/cli/lib/sync/projects.js"]
            image: 887044485231.dkr.ecr.eu-west-1.amazonaws.com/biodiversity-cli/testing:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: biodiversity-cli-secrets
              - configMapRef:
                  name: biodiversity-cli-config
          restartPolicy: Never