apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: biodiversity-cli-opensearch-daily-sync
  namespace: testing
spec:
  # once a day on 03:08 AM UTC
  schedule: '8 3 * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: biodiversity-cli-opensearch-daily-sync
            command: ["node", "--experimental-specifier-resolution=node", "apps/cli/lib/search/daily.js"]
            image: 887044485231.dkr.ecr.eu-west-1.amazonaws.com/biodiversity-cli:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: biodiversity-cli-secrets
              - configMapRef:
                  name: biodiversity-cli-config
          restartPolicy: Never
