apiVersion: batch/v1
kind: Job
metadata:
  name: biodiversity-cli-migrate-JOB_NUMBER
  namespace: testing
spec:
  template:
    metadata:
      labels:
        job_group: biodiversity-cli-migrate
    spec:
      containers:
      - name: biodiversity-cli-migrate-JOB_NUMBER
        command: ["node", "--experimental-specifier-resolution=node", "apps/cli/lib/db/reset-migrate-seed.js", "--", "--path=03-preload,04-user-data-mock"]
        image: 887044485231.dkr.ecr.eu-west-1.amazonaws.com/biodiversity-cli/testing:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: biodiversity-cli-secrets
          - configMapRef:
              name: biodiversity-cli-config
      restartPolicy: Never
  backoffLimit: 1