apiVersion: batch/v1
kind: Job
metadata:
  name: biodiversity-cli-sync-arbimon-JOB_NUMBER
  namespace: testing
spec:
  template:
    metadata:
      labels:
        job_group: biodiversity-cli-sync-arbimon
    spec:
      containers:
      - name: biodiversity-cli-sync-arbimon-JOB_NUMBER
        command: ["node", "--experimental-specifier-resolution=node", "apps/cli/lib/sync/sync-arbimon.js"]
        image: 887044485231.dkr.ecr.eu-west-1.amazonaws.com/biodiversity-cli/testing:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: biodiversity-cli-secrets
          - configMapRef:
              name: biodiversity-cli-config
      restartPolicy: Never
  backoffLimit: 1