// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    IconCustomAngleDown: typeof import('~icons/custom-icons/angle-down')['default']
    IconCustomChevronLeft: typeof import('~icons/custom-icons/chevron-left')['default']
    IconCustomChevronRight: typeof import('~icons/custom-icons/chevron-right')['default']
    IconCustomDownload: typeof import('~icons/custom-icons/download')['default']
    IconCustomLinkout: typeof import('~icons/custom-icons/linkout')['default']
    IconFaCheck: typeof import('~icons/fa/check')['default']
    IconFaChevronDown: typeof import('~icons/fa/chevron-down')['default']
    IconFaChevronUp: typeof import('~icons/fa/chevron-up')['default']
    IconFaClose: typeof import('~icons/fa/close')['default']
    IconFaCubes: typeof import('~icons/fa/cubes')['default']
    IconFaExclamationTriangle: typeof import('~icons/fa/exclamation-triangle')['default']
    IconFaInfoCircle: typeof import('~icons/fa/info-circle')['default']
    IconFaMapMarker: typeof import('~icons/fa/map-marker')['default']
    IconFaPause: typeof import('~icons/fa/pause')['default']
    IconFaPlay: typeof import('~icons/fa/play')['default']
    IconFasAngleRight: typeof import('~icons/fa-solid/angle-right')['default']
    IconFasCaretRight: typeof import('~icons/fa-solid/caret-right')['default']
    IconFasChevronLeft: typeof import('~icons/fa-solid/chevron-left')['default']
    IconFasChevronRight: typeof import('~icons/fa-solid/chevron-right')['default']
    IconFasClock: typeof import('~icons/fa-solid/clock')['default']
    IconFasEllipsisV: typeof import('~icons/fa-solid/ellipsis-v')['default']
    IconFasFilter: typeof import('~icons/fa-solid/filter')['default']
    IconFasSearch: typeof import('~icons/fa-solid/search')['default']
    IconFasSpinner: typeof import('~icons/fa-solid/spinner')['default']
    IconFasTag: typeof import('~icons/fa-solid/tag')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
