# !WARNING: MANUAL ACTION REQUIRED!

# You must keep these file in sync:
# - `tools/deployment/api/production/config.yaml` -- CONFIG ONLY
# - `tools/deployment/api/staging/config.yaml` -- CONFIG ONLY
# - `tools/deployment/api/testing/config.yaml` -- CONFIG ONLY
# - `apps/api/.env.example` -- CONFIG & SECRETS
# - `apps/api/src/_services/env/keys.ts` -- CONFIG & SECRETS

apiVersion: v1
kind: ConfigMap
metadata:
  name: biodiversity-api-config
  namespace: testing
data:
  ## Config
  AWS_S3_BUCKET_NAME: arbimon-development
  AWS_S3_BUCKET_REGION: eu-west-1
  AWS_OSS_REGION: eu-west-1
  ARBI_ASSISTANT_BASE_URL: https://adk-default-service-name-435981252511.europe-west1.run.app
  ARBIMON_LEGACY_API_BASE_URL: https://dev.arbimon.org/legacy-api
  CORE_API_BASE_URL: https://staging-api.rfcx.org
  OPENSEARCH_ENABLED: "true"
  SUPER_USER_EMAILS: support@rfcx.org,scientist-super@rfcx.org,turk@rfcx.org
  BACKUP_TIMEFRAME_LIMIT: "5m"
  KUBERNETES_NAMESPACE: testing
