# !WARNING: MANUAL ACTION REQUIRED!

# You must keep these file in sync:
# - `tools/deployment/api/production/config.yaml` -- CONFIG ONLY
# - `tools/deployment/api/staging/config.yaml` -- CONFIG ONLY
# - `tools/deployment/api/testing/config.yaml` -- CONFIG ONLY
# - `apps/api/.env.example` -- CONFIG & SECRETS
# - `apps/api/src/_services/env/keys.ts` -- CONFIG & SECRETS

apiVersion: v1
kind: ConfigMap
metadata:
  name: biodiversity-api-config
  namespace: testing
data:
  ## Config

  PUERTO_RICO_PROJECT_SLUG: puerto-rico
