version: "3.2"
services:
  timescaledb-test:
    image: "timescale/timescaledb:latest-pg12"
    ports:
      - "5434:5432"
    volumes:
      - data-timescaledb-test:/var/lib/postgresql/data
      - ./init.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user_cli
      - POSTGRES_PASSWORD=test
    command: '-c max_connections=200'
  s3mock-test:
    image: adobe/s3mock
    environment:
      - initialBuckets=bucket
    ports:
      - "9092:9090"
  search-test:
    image: opensearchproject/opensearch:2.11.0
    environment:
      discovery.type: single-node
      plugins.security.disabled: true
      bootstrap.memory_lock: true
    # healthcheck:
    #   interval: 10s
    #   retries: 80
    #   test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9202:9200"
    volumes:
      - data-search-test:/usr/share/opensearch/data
volumes:
  data-timescaledb-test:
  data-search-test:
