version: "3.2"
services:
  timescaledb:
    image: "timescale/timescaledb:latest-pg12"
    ports:
      - "5445:5432"
    volumes:
      - data-timescaledb:/var/lib/postgresql/data
      - ./init.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test

  s3mock:
    image: adobe/s3mock
    environment:
      - initialBuckets=bucket
    ports:
      - "9090:9090"

volumes:
  data-timescaledb:
