name: 'CI Nightly'
on:
  workflow_dispatch:
  schedule:
    # Every weekday at 01:37 UTC (08:37 in Thailand) https://crontab.guru
    - cron:  '37 1 * * 1-5'
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:

  build:
    name: 'Build'
    uses: ./.github/workflows/reusable-build.yaml
    with:
      runs-on: ubuntu-22.04
      lint: false
      test: false

  test:
    name: 'Test'
    needs: [build]
    uses: ./.github/workflows/reusable-int-test.yaml
    with:
      runs-on: ubuntu-22.04

  notify:
    name: 'Notify'
    if: ${{ always() }}
    needs: [build, test]
    uses: rfcx/cicd/.github/workflows/notify.yaml@master
    with:
      workflow-id: ci-nightly.yaml
      status: ${{ needs.build.result == 'success' && needs.test.result == 'success' && 'success' || 'failure' }}
      notification-title: 'CI: Arbimon Integration Test'
      notification-footer: "Build: ${{ needs.build.outputs.build-outcome || 'n/a' }} | Migrate+Seed: ${{ needs.test.outputs.migrate-seed-outcome || 'n/a' }} | Test: ${{ needs.test.outputs.test-outcome || 'n/a' }}"
      always: true
    secrets:
      slack-webhook: ${{ secrets.SLACK_ALERT_ARBIMON_WEBHOOK }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

