name: 'CI Nightly'
on:
  workflow_dispatch:
  schedule:
    # Every weekday at 01:37 UTC (08:37 in Thailand) https://crontab.guru
    - cron:  '37 1 * * 1-5'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  prepare:
    name: 'Prepare'
    uses: ./.github/workflows/reusable-notify-prepare.yml
    with:
      workflow-id: ci-nightly.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: 'Build'
    uses: ./.github/workflows/reusable-build.yml
    with:
      runs-on: ubuntu-20.04
      lint: false
      test: false

  test:
    name: 'Test'
    needs: [prepare, build]
    uses: ./.github/workflows/reusable-int-test.yml
    with:
      runs-on: ubuntu-20.04

  notify:
    name: 'Notify'
    if: ${{ always() }}
    needs: test
    uses: ./.github/workflows/reusable-notify-send.yml
    with:
      branch-name: ${{ needs.prepare.outputs.branch-name }}
      workflow-id: ci-nightly.yml
      previous-run-id: ${{ needs.prepare.outputs.previous-run-id }}
      notification-title: 'CI: Bio Integration Test'
      notification-footer: 'Build: ${{ needs.build.outputs.build-outcome }} | Integration Test: ${{ needs.build.outputs.test-outcome }}'
    secrets:
      slack-webhook: ${{ secrets.SLACK_ALERT_BIODT_WEBHOOK }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

