name: 'CI On Push'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:

  build:
    name: 'Build'
    uses: ./.github/workflows/reusable-build.yaml
    with:
      runs-on: ubuntu-22.04

  notify:
    name: 'Notify'
    if: ${{ github.event_name != 'pull_request' }}
    needs: [build]
    uses: rfcx/cicd/.github/workflows/notify.yaml@master
    with:
      workflow-id: ci-on-push.yaml
      status: ${{ needs.build.result }}
      notification-title: 'CI: Arbimon Build-Lint-Test'
      notification-footer: "Build: ${{ needs.build.outputs.build-outcome || 'n/a' }} | Lint: ${{ needs.build.outputs.lint-outcome || 'n/a' }} | Unit Test: ${{ needs.build.outputs.test-outcome || 'n/a' }}"
    secrets:
      slack-webhook: ${{ secrets.SLACK_ALERT_ARBIMON_WEBHOOK }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
