name: 'Create CLI job'
on:
  workflow_dispatch:
    inputs:
      job:
        description: Job
        type: choice
        options:
        - 'sync-daily'
        - 'sync-incremental'
        - 'export-csv'
        - 'opensearch-full-reindex'
        - 'recreate-opensearch-indexes'
        required: true
      environment:
        description: Environment (namespace)
        type: choice
        default: 'production'
        options:
        - 'production'
        - 'staging'
        - 'testing'
        required: true
jobs:
  create-job:
    runs-on: deployment-runner
    env:
      ECR_REGISTRY: '887044485231.dkr.ecr.eu-west-1.amazonaws.com'
      ECR_REPO: 'biodiversity-cli'
    steps:
      - name: 'Setup: ENV job'
        # v0 (0.3.0) @ 23 Oct 2022 https://github.com/kanga333/variable-mapper/tags
        uses: kanga333/variable-mapper@3681b75f5c6c00162721168fb91ab74925eaebcb
        with:
          key: '${{ inputs.job }}'
          map: |
            {
              "sync-daily": {
                "JOB_NAME": "biodiversity-cli-sync-daily-user",
                "NODE_COMMAND": "apps/cli/lib/sync/daily.js"
              },
              "sync-incremental": {
                "JOB_NAME": "biodiversity-cli-sync-incremental-user",
                "NODE_COMMAND": "apps/cli/lib/sync/incrementally.js"
              },
              "export-csv": {
                "JOB_NAME": "biodiversity-cli-export-csv",
                "NODE_COMMAND": "apps/cli/lib/export/export-csv.js"
              },
              "opensearch-full-reindex": {
                "JOB_NAME": "biodiversity-cli-opensearch-full-reindex",
                "NODE_COMMAND": "apps/cli/lib/search/sync-all.js"
              },
              "recreate-opensearch-indexes": {
                "JOB_NAME": "biodiversity-cli-recreate-opensearch-indexes",
                "NODE_COMMAND": "apps/cli/lib/search/recreate-indexes.js"
              }
            }

      - name: 'Setup: Generate job unique number'
        run: echo "JOB_NUMBER=$(date +%s)" >> $GITHUB_ENV
    
      - name: 'Deploy: Generate job definition file'
        run: |
          cat <<EOF > job.yaml
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: ${{ env.JOB_NAME }}-${{ env.JOB_NUMBER }}
          spec:
            ttlSecondsAfterFinished: 86400
            template:
              spec:
                containers:
                - name: ${{ env.JOB_NAME }}
                  command: ["node", "--experimental-specifier-resolution=node", "${{ env.NODE_COMMAND }}"]
                  image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ inputs.environment }}
                  imagePullPolicy: Always
                  envFrom:
                    - secretRef:
                        name: biodiversity-cli-secrets
                    - configMapRef:
                        name: biodiversity-cli-config
                restartPolicy: Never
            backoffLimit: 0
          EOF
          cat job.yaml

      - name: 'Deploy: Create job'
        # v1 (1.28.2) @ 19 Oct 2023 https://github.com/actions-hub/kubectl/tags
        uses: actions-hub/kubectl@6fd9eb2486a67fab3b011befdf3cfcc4e64d9655
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_SUPER }}
        with:
          args: apply -f job.yaml -n ${{ inputs.environment }}
