name: 'Build'
on:
  workflow_dispatch:
  push:
    branches-ignore: # ignore branches using the CD workflow
      - master
      - staging
jobs:
  Main:
    runs-on: ubuntu-20.04
    steps:
      - id: latest_run
        name: 'Notify: Get status of previous run'
        uses: octokit/request-action@v2.1.0
        if: always()
        with:
          route: GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
          owner: rfcx
          repo: biodiversity-analytics
          workflow_id: build.yml
          per_page: 2
          branch: ${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: 'echo ${{ fromJson(steps.latest_run.outputs.data).workflow_runs[0] }}'
      - run: 'echo ${{ fromJson(steps.latest_run.outputs.data).workflow_runs[1] }}'
      - run: 'echo ${{ fromJson(steps.latest_run.outputs.data).workflow_runs[1].status }}'
