name: 'Notify: Prepare'
on:
  workflow_call:
    inputs:
      workflow-id:
        description: Workflow ID (e.g. build.yml)
        type: string
        required: true
    secrets:
      github-token:
        description: GitHub Token
        required: true
    outputs:
      branch-name: ${{ steps.branch.outputs.branch-name }}
      previous-run-id: ${{ fromJson(steps.workflow-runs.outputs.data).workflow_runs[1].id }}
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Setup: Get branch name'
        id: branch
        run: |
          if [[ "${{ github.event_name }}" = "pull_request" ]]; then echo "::set-output name=branch-name::`echo ${GITHUB_HEAD_REF}`"; else echo "::set-output name=branch-name::`echo ${GITHUB_REF#refs/heads/}`"; fi
          
      - name: 'Setup: Get ID of previous run' # Need to execute this early (before another run starts)
        id: workflow-runs
        uses: octokit/request-action@7e93b91076fad3920c29d44eb2a6311d929db3dd
        # v2 (2.1.0) @ 03 Dec 2021 https://github.com/octokit/request-action/tags
        with:
          # https://docs.github.com/en/rest/reference/actions#list-workflow-runs
          route: GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
          owner: rfcx
          repo: biodiversity-analytics
          workflow_id: ${{ inputs.workflow-id }}
          per_page: 2
          branch: ${{ steps.branch.outputs.branch-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
