# !WARNING: MANUAL ACTION REQUIRED!

# You must keep these file in sync:
# - `tools/deployment/cli/production/config.yaml` -- CONFIG ONLY
# - `tools/deployment/cli/staging/config.yaml` -- CONFIG ONLY
# - `tools/deployment/cli/testing/config.yaml` -- CONFIG ONLY
# - `tools/deployment/cli/secrets.example.yaml` -- SECRETS ONLY
# - `apps/cli/.env.example` -- BOTH
# - `apps/cli/src/_services/env/keys.ts` -- BOTH

apiVersion: v1
kind: Secret
metadata:
  name: biodiversity-cli-secrets
  namespace: testing # Change this as needed
type: Opaque
data:
  ## Secrets

  # WARNING: Do not commit secrets in this example file
  # Only specify keys (leave values blank
  # In your real secrets.yaml, values must be BASE64 encoded

  ARBIMON_DB_DBNAME:
  ARBIMON_DB_HOSTNAME:
  ARBIMON_DB_PASSWORD:
  ARBIMON_DB_USER:

  BIO_DB_DBNAME:
  BIO_DB_HOSTNAME:
  BIO_DB_PASSWORD:
  BIO_DB_PORT:
  BIO_DB_SSL_ENABLED:
  BIO_DB_USER:

  IUCN_TOKEN:
